### PR TITLE
Supporting PT 1.8

### PR DESCRIPTION
**Pull request by leleamol**
### Description of changes:
The PR contains code change to support the PT 1.8

The change is mainly due to the fact the PT1.8 has changed the signatures of private methods in torch autograd profiler.

There is no other functionality changes.
The integration tests suite was run against this code change with DLC that contained the updated torch 1.8 binary wheel.

Here is the link: https://tiny.amazon.com/gwxvxtl8/IsenLink 

Testing:

Ran the unit tests in the DLC container with PT1.8. The unit tests include eagleeye zero code change tests too.

#### Style and formatting:

I have run `pre-commit install` to ensure that auto-formatting happens with every commit.

#### Issue number, if available

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by ndodda-amazon — CHANGES_REQUESTED** [review]
Changes look good to me, will approve after the CI passes.

Can we also introduce another PR CI build for PT 1.8 and add it to the CI?

**Comment by leleamol** [comment]
The codebuild project for 1.8 is already created. Would need help in setting up the webhook for PR CI

**Comment by ndodda-amazon** [comment]
> The codebuild project for 1.8 is already created. Would need help in setting up the webhook for PR CI

To clarify, I meant a build to run the unit tests for PT 1.8. But as we discussed offline, you've manually run the unit tests in the PT 1.8 container, which is good. 

Please retrigger the CI, I'll approve once tests pass.

**Review by ndodda-amazon — APPROVED** [review]
LGTM, good work!

**Pull request closed without merging**
