### PR TITLE
make the processing function more robust to handle corrupted json lin…

### PR DESCRIPTION
**Pull request by zaoliu-aws**
A small change to make the processing function more robust.

### CODE REVIEW

**Comment by zaoliu-aws** [comment]
@johnbensnyder and @jleeleee , please take a look to see if it makes sense. It is a very small change.

**Review by johnbensnyder — APPROVED** [review]

**Comment by zaoliu-aws** [comment]
added more information based on @jleeleee 's input.

**Review by jleeleee — APPROVED** [review]
nit: probably could be debug level, but shouldn't matter too much

**Comment by zaoliu-aws** [comment]
@jleeleee , changed to debug level.

**Pull request merged**
